### ISSUE TITLE
responses?

### ISSUE THREAD

**Issue by robothomessydney** [nirnachmani/Pixie-Plus-for-Home-Assistant#6]
Hello, We posted some questions, but no response?
are you managing this integration anymore?

**Comment by nirnachmani** [comment]
Hi, sorry, I am very busy this days. The JavaScriptKey was in the communication between the Pixie Plus app and the server, like the other keys. It's been quite a while now since I found those keys and I don't remember exactly were it was but if you look at the back and forth communication it is there.
